package ar.edu.unlu.poo.modelo.evento;

public enum Eventos {
    ACCION_REALIZADA,
    SALDO_INSUFICIENTE,
    JUGADOR_YA_INSCRIPTO,
    LA_MESA_YA_INICIO,
    SIN_LUGARES_DISPONIBLES,
    JUGADOR_CONFIRMADO,
    YA_ASEGURADO, ULTIMA_MANO, NO_ES_TURNO_INICIAL, NO_ES_SU_TURNO, DEALER_NO_CUMPLE, MANO_YA_ASEGURADA, MANO_NO_CUMPLE, JUGADOR_EN_LA_MESA, MESA_ACEPTANDO_INSCRIPCIONES, JUGADOR_YA_EN_LISTA, JUGADOR_NO_ESTA, GENTE_ESPERANDO,


}
