package ar.edu.unlu.poo.modelo.eventos;

public enum Eventos {
    JUGADOR_YA_INSCRIPTO,
    SIN_LUGARES_DISPONIBLES,
    LA_MESA_YA_INICIO,
    ACCION_REALIZADA,
    JUGADOR_CONFIRMADO,
    ULTIMA_MANO,
    SITUACION_INNESPERADA,
    NO_ES_SU_TURNO,
    NO_ES_TURNO_INICIAL,
    DEALER_NO_CUMPLE_CONDICION,
    SALDO_INSUFICIENTE,
    MANO_NO_CUMPLE_CONDICION,


}
