package ar.edu.unlu.poo.vista.Consola;

public enum Menu {
    LOGGIN,
    CARGAR_JUGADORES,
    CREAR_JUGADOR,
    CASINO,
    ACCIONES_CASINO,
    CONECTADOS,
    RANKING,
    PEDIR_APUESTA_LISTA,
    PEIDR_APUESTA_MESA,
    MESA,
    INSCRIPCIONES,
    REPARTIENDO,
    TURNO_JUGADOR,
    TURNO_DEALER,
    GANANCIAS_REPARTIDAS,
    FINALIZAR,
    PEDIR_APUESTA_MANO,
    PEDIR_APUESTA_CONFIRMACION,
    ELIMINAR_MANO,
    ESPERANDO;



}
